export const notableAreas = [
  'Abokobi Madina',
  'Accra Metropolis',
  'Ada East',
  'Ada West',
  'Adenta Municipal',
  'Anyaa',
  'Ashaiman Municipal',
  'Ayawaso Central',
  'Ayawaso East',
  'Ayawaso North',
  'Ayawaso West',
  'Ga Central Municipal',
  'Ga East Municipal',
  'Ga North Municipal',
  'Ga West Municipal',
  'Ga South Municipal',
  'Kpone Katamanso Municipal',
  'La Dade-Kotopon Municipal',
  'La Nkwantanang Madina Municipal',
  'Ledzokuku-Krowor Municipal',
  'Ningo Prampram',
  'Okaikoi North',
  'Okaikoi South',
  'Ablekuma Central',
  'Ablekuma North',
  'Ablekuma West',
  'Ablekuma South',
  'Shai Osudoku',
  'Tema Metropolis',
  'Tema West Municipal',
  'Weija Gbawe Municipal',
  'Osu Klottey',
  'Teshie',
  'Nungua',
  'Airport Residential Area',
  'Cantonments',
  'Labone',
  'Dzorwulu',
  'East Legon',
  'West Legon',
  'North Legon',
  'Haatso',
  'Ashaley Botwe',
  'Adabraka',
  'Circle',
  'Ridge',
  'Roman Ridge',
  'Achimota',
  'Dansoman',
  'Kasoa',
  'Bortianor',
  'Sakumono',
  'Spintex',
  'Teshie-Nungua Estates',
  'Agbogba',
  'Kanda',
  'Kokomlemle',
  'Labadi',
  'Chorkor',
  'Mamprobi',
  'Kwashieman',
  'Mallam',
  'Gbawe',
  'McCarthy Hill',
  'Kwabenya',
  'Amasaman',
  'Ofankor',
  'Pokuase',
  'Ashongman',
  'Kwashieman',
  'Tesano',
  'Darkuman',
  'Bubuashie',
  'Korle Gonno',
  'Korle Bu',
  'James Town',
  'Ussher Town',
  'Teshie-Nungua',
  'Dodowa',
  'Agbogbloshie',
  'Kaneshie',
  'Odorkor',
  'Abeka',
  'Awoshie',
  'Abelemkpe',
  'North Ridge',
  'South Ridge',
  'Dome',
  'Tudu',
  'Nii Boi Town',
  'Sekondi',
  'Takoradi',
  'Effia-Kwesimintsim',
  'Anaji',
  'Kwesimintsim',
  'Apowa',
  'Shama',
  'Kojokrom',
  'Essikado',
  'Fijai',
  'Ketan',
  'Tanokrom',
  'New Takoradi',
  'Tarkwa',
  'Eshiem',
  'Aboadze',
  'Inchaban',
  'Agona Nkwanta',
  'Kansaworodo',
  'Whindo',
  'Mpintsin',
  'Effiakuma',
  'Sekondi Naval Base',
  'Ahanta West',
  'Wassa East',
  'Takoradi Market Circle',
].sort();
